name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

concurrency:
  group: ci-${{ github.ref }}-lint
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Run tests
        run: make test
